apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-init-secrets
  namespace: keycloak
  creationTimestamp: null
spec:
  encryptedData:
    KEYCLOAK_ADMIN: AgA2R2S484/VQytyn6AQiSTOu3h1cjOTT4ALMz9yZ3qfhtiaqB54s41xswiNNzoDuGA4RGDIPltR4ZU5illBGV1A1k2M66XHkqiCQncaJElg0mEbk/zmGnArJ2BZeuRmTeIsyJq4pnjs+2XYV6Zd9dwBs9sSiTcYztij1nz7ChPVZeLS3F1B0HWveahQ++eSUhDMxmg4I5TvrqTBA5j7YiP4HARb0YtyjWKHMoXwBRQXFa6SNGqHWmYa5m158E2J6OVHRFF0rGWdE8tFiPsgHSWS7AghX4vUJKOseDn5QLwPenyrEnqjGNOBgcfU77HMwMule9Nyx2qbGwnGRoy5UC2qMQuWue80b1a0J+Eyu1kRAo6UlmogXnjl5R+bm5qAJdSpDwVtdGD6vFruW9jenJPeTh8bxZMKyIrsWw8NJkc6xWGL7vx3XKmWIhbJKlUpYnka9/QR4ipflLy8ZSAfeXD65A3Eh6Vp9IfgD1vXAiH2gzdut0J5PCh68Ooo8V/amewG5ke2QWI33LlxOeuSU3vlWzj9wryzjWHFvKN2SlG32Nf+DRYWV7C7ssnJoS3YVYTpcq5wrBU9ACmPCuxs+mUW7JXVlkhZa1LfWJyxIZyz8pyWd5BWIpXNVIGYWxIsYHWhp/keGyiCbPAydYsb//vv92S9Viz7I4MI2Aio9FC6MzXcUlGNblzh2tS/QHyd8mn7H0kh0w==
    KEYCLOAK_ADMIN_PASSWORD: AgDCd5npVZtoBdvQueFN/grILxiL6vrxFKcWoGy5qOJQEQoSlNl+XVwIi5e8uXHOZbvJcGSODbwez32laP2jQBbtbrMZvAVCqZhZLOkwjimWSBa3RhVXJ1cLK0WktrmD+o4kIh5gODcYhd1yjW8YW1C75Y0OvtxaIYsNBqBZlV55QdmKKVTGv9sitah3GqDa54+zpoa7GoOXB3FrRuhAB3GHuDOjHN/udc8jmhB52d4pTZmj9c30/DgCw8jM7zwmvk5jWVWjwRUMqkhIgQU1OIx5q2i75Rz4DuxtiEH3o5I/KosujDCjQ/s9dlSsw1QwJdBJvhFT+EornHGjK8luIGVsNzsTZS/JH4Z7BfK9K3OPy2B+FBCdNsx59oAulKNWop8WTdOIyu/KVzROkng4IHAtB/WLrXsIE4sk6wqZwQGfVr2LdDqUFx+mRfOkCUBr7ByBUqXlBUstmDZQEp4IyUN17JjIUno2q2r2qARIsnEt9vrB3Sxyma4ZjDvuNqLzYA4b3YPJtFzOitIyk1lyhGlijpHD8Lt6Pqp1X2DsGRhC095fcyhi/Tu241u6z3jBp2mgGvcvpTo2qYXaOddEkqxF2kFAEQmeFf17u3AMJQCjV1PneppLpjLUT246XkQufI/yrM1y/t5+sBQurU9mlJyqVH7ToiCEJ7f4yldakeAV9QkqErj3Kk/X8KCWBzZBgLTb/hu/gD3q9fU=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-init-secrets
      namespace: keycloak

