apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant-config
  namespace: daybreak-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
