apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - ../../base
  - ../../../components/argocd/apps/overlays/rhdp-4.9

patches:
  - path: patch-applicationset-repo-revision.yaml
    target:
      group: argoproj.io
      kind: ApplicationSet
      version: v1alpha1
  - path: patch-application-repo-revision.yaml
    target:
      group: argoproj.io
      kind: Application
      version: v1alpha1
