apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3scale
spec:
  destination:
    namespace: daybreak-gitops
    server: https://kubernetes.default.svc
  project: shared-services
  source:
    path: components/argocd/shared-services/3scale/overlays/default
    repoURL: https://github.com/redhat-guidehouse-daybreak/openshif-cluster-bootstrap-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - Replace=false
      - CreateNamespace=true
  ignoreDifferences:
    - group: bitnami.com
      kind: SealedSecret
      jsonPointers:
        - /metadata/type