apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../tenants/fhir/components/argocd/applications/overlays/default/
  - ../../../../tenants/kafka/components/argocd/applications/overlays/default/
  - ../../../../tenants/risk-assessment/components/argocd/applications/overlays/default/

resources:
  - cluster-config-app-of-apps.yaml
  - cluster-operators-applicationset.yaml
  #- rbac-applicationset.yaml
  - psql-application.yaml
  - keycloak-application.yaml
  - 3scale-application.yaml