apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: risk-assessment-guidehouse-viewers
  namespace: risk-assessment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: guidehouse
