apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: clusterresourceoverride
  namespace: clusterresourceoverride-operator
spec:
  channel: patch-me-see-overlays-dir
  name: clusterresourceoverride
  source: redhat-operators
  sourceNamespace: openshift-marketplace
