---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-logging

resources:
  - namespace.yaml
  - enable-console-plugin-job.yaml
  - enable-console-plugin-rbac.yaml
  - enable-console-plugin-sa.yaml
  - operator-group.yaml
  - subscription.yaml