apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperAccount
metadata:
  name: daybreak
spec:
  orgName: daybreak
---
apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperUser
metadata:
  name: daybreak
spec:
  developerAccountRef:
    name: daybreak
  email: cpeng@guidehouse.com
  passwordCredentialsRef:
    name: 3scale-developer-user-secret
  role: admin
  username: daybreak