apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: daybreak-gitops

bases:
  - ./cluster-role-binding.yaml
  - ./openshift-gitops-cr.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/rbac/policy
        value: |
          g, system:cluster-admins, role:admin
          g, cluster-admins, role:admin
    target:
      kind: ArgoCD
  - path: patch-resource-customizations.yaml
    target:
      kind: ArgoCD
