apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: sso-keycloak
  labels:
    app: sso
  namespace: rh-sso
spec:
  externalAccess:
    enabled: true
  keycloakDeploymentSpec:
    imagePullPolicy: Always
  postgresDeploymentSpec:
    imagePullPolicy: Always
  instances: 1